defended = []		#batsman, bowler, impact, reason
left_alone = []		#batsman, bowler, impact, reason
beaten = []			#batsman, bowler, impact, reason
edged = []			#batsman, bowler, impact, reason
caught = []			#batsman, bowler, fielder, impact, reason
runout = []			#batsman, manout, bowler, fielder, impact, reason
stumped = []		#batsman, bowler, fielder, impact, reason
bowled = []			#batsman, bowler, impact, reason
lbw = []			#batsman, bowler, impact, reason
boundary_bat = []	#batsman, bowler, runs, impact, reason
runs_bat = []		#batsman, bowler, runs, impact, reason
boundary_extra = []	#batsman, bowler, freason, impact, reason
runs_extra = []		#batsman, bowler, freason, impact, reason
catch_drop = []		#batsman, bowler, fielder, impact, reason
stump_miss = []		#batsman, bowler, fielder, impact, reason
runout_miss = []	#batsman, bowler, fielder, impact, reason
bouncer = []		#batsman, bowler, impact, reason
yorker = []			#batsman, bowler, impact, reason
overthrow = []		#batsman, bowler, fielder, impact, reason
save = []			#batsman, bowler, fielder, impact, reason
poor = []			#batsman, bowler, fielder, impact, reason
free = []			#batsman, bowler, fielder, impact, reason
missed_opp = 
